server:
  port: 8781
spring:
  application:
    name: msa-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/yekki/msa-config.git
          search-paths: /**


eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: config
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/

