server:
  port: 8781
spring:
  application:
    name: msa-config
  rabbitmq:
    host: config
    port: 5672
    username: gniu
    password: gniu
  cloud:
    bus:
      trace:
        enabled: true
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/yekki/msa-config.git
          search-paths: /**
#  security:
#    user:
#      name: admin
#      password: admin

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: config
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/